#pragma once
#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#define GLFW_INCLUDE_VULKAN
#include "json.hpp"
#include "util.h"
#include <GLFW/glfw3.h>
#include <array>
#include <chrono>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <glm/glm.hpp>
#include <iostream>
#include <set>
#include <sstream>
#include <string>
#include <vector>
#include <vulkan/vulkan.h>
